### DISCUSSION TITLE
How to read a `List` from a data source context?

### DISCUSSION THREAD

**Discussion by PaulRBerg** [graphprotocol/graph-tooling#2025] [Q&A] [answered]
The [docs](https://thegraph.com/docs/en/subgraphs/developing/creating/graph-ts/api/#datasourcecontext-in-manifest) mention the possibility of defining an item of type `List` in the YAML subgraph manifest:

```yaml
dataSources:
  - kind: ethereum/contract
    name: ContractName
    network: mainnet
    context:
      list_example:
        type: List
        data:
          - type: "BigInt"
            data: "1"
          - type: "BigInt
            data: "2"
          - type: "BigInt"
            data: "3"
```

But there is no guidance provided for how to read that list in an AssemblyScript mapping.

I wrote it like this but I'm not sure if it's correct:

```typescript
export function getStringArray(key: string): string[] {
  const context = dataSource.context();
  const value = context.get("list_example");
  return value!.toStringArray();
}
```

Can anyone from Edge & Node please confirm this?
