### ISSUE TITLE
`graph-cli 0.38.0` renames contract events during `graph-init`

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-tooling#1136]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

`graph cli-v0.38.0` renames contract events during `graph init`, causing those events in the `subgraph.yaml` not to trigger when the subgraph is deployed. The event in the ABI is also renamed
![Screenshot 2023-02-24 at 4 29 00 PM](https://user-images.githubusercontent.com/73024324/221218782-3471a78b-1163-41cc-8237-cab4f372a9cb.png)
![Screenshot 2023-02-24 at 4 26 37 PM](https://user-images.githubusercontent.com/73024324/221218800-d89c9fa5-2958-476a-aca1-aef0d73501a5.png)

### Reproduction

none

### Steps to Reproduce the Bug or Issue

1. Run `graph init` to initialize a new subgraph.
2. Follow the wizard with the configurations below. 
3. After the initialization process, go to the subgraph directory
4. Open the `subgraph.yaml` and look at the events on the second contract we added
5. The events, both in the ABI, are prefixed with the contract name which shouldn't be the case. 

![Screenshot 2023-02-24 at 4 24 41 PM](https://user-images.githubusercontent.com/73024324/221219086-9e86f7de-dd8f-4b06-92ce-8c1a95a15c08.png)

### Expected behavior

![Screenshot 2023-02-24 at 4 28 26 PM](https://user-images.githubusercontent.com/73024324/221219865-1c7b6a4e-81fd-4389-82ec-646617c74d0e.png)

### Platform

- OS: macOS  13.2.1
- NodeJS: v18.12.0
- `@graphprotocol/*` version(s): @graphprotocol/graph-cli": "0.38.0

### Subgraph Manifest

```yaml
specVersion: 0.0.5
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: DirectLoanFixedOffer
    network: mainnet
    source:
      address: "0xf896527c49b44aAb3Cf22aE356Fa3AF8E331F280"
      abi: DirectLoanFixedOffer
      startBlock: 0
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - AdminFeeUpdated
        - ERC20Permit
        - LoanLiquidated
        - LoanRenegotiated
        - LoanRepaid
        - LoanStarted
        - MaximumLoanDurationUpdated
        - OwnershipTransferred
        - Paused
        - Unpaused
      abis:
        - name: DirectLoanFixedOffer
          file: ./abis/DirectLoanFixedOffer.json
      eventHandlers:
        - event: AdminFeeUpdated(uint16)
          handler: handleAdminFeeUpdated
        - event: ERC20Permit(indexed address,bool)
          handler: handleERC20Permit
        - event: LoanLiquidated(indexed uint32,indexed address,indexed
            address,uint256,uint256,uint256,uint256,address)
          handler: handleLoanLiquidated
        - event: LoanRenegotiated(indexed uint32,indexed address,indexed
            address,uint32,uint256,uint256,uint256)
          handler: handleLoanRenegotiated
        - event: LoanRepaid(indexed uint32,indexed address,indexed
            address,uint256,uint256,uint256,uint256,uint256,address,address,address)
          handler: handleLoanRepaid
        - event: LoanStarted(indexed uint32,indexed address,indexed
            address,(uint256,uint256,uint256,address,uint32,uint16,uint16,address,uint64,address,address),(address,uint16,uint16))
          handler: handleLoanStarted
        - event: MaximumLoanDurationUpdated(uint256)
          handler: handleMaximumLoanDurationUpdated
        - event: OwnershipTransferred(indexed address,indexed address)
          handler: handleOwnershipTransferred
        - event: Paused(address)
          handler: handlePaused
        - event: Unpaused(address)
          handler: handleUnpaused
      file: ./src/direct-loan-fixed-offer.ts
  - kind: ethereum
    name: DirectLoanFixedOfferRedeploy
    network: mainnet
    source:
      address: "0x8252Df1d8b29057d1Afe3062bf5a64D503152BC8"
      abi: DirectLoanFixedOfferRedeploy
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - DirectLoanFixedOfferRedeployAdminFeeUpdated
        - DirectLoanFixedOfferRedeployERC20Permit
        - DirectLoanFixedOfferRedeployLoanLiquidated
        - DirectLoanFixedOfferRedeployLoanRenegotiated
        - DirectLoanFixedOfferRedeployLoanRepaid
        - DirectLoanFixedOfferRedeployLoanStarted
        - DirectLoanFixedOfferRedeployMaximumLoanDurationUpdated
        - DirectLoanFixedOfferRedeployOwnershipTransferred
        - DirectLoanFixedOfferRedeployPaused
        - DirectLoanFixedOfferRedeployUnpaused
      abis:
        - name: DirectLoanFixedOfferRedeploy
          file: ./abis/DirectLoanFixedOfferRedeploy.json
      eventHandlers:
        - event: DirectLoanFixedOfferRedeployAdminFeeUpdated(uint16)
          handler: handleDirectLoanFixedOfferRedeployAdminFeeUpdated
        - event: DirectLoanFixedOfferRedeployERC20Permit(indexed address,bool)
          handler: handleDirectLoanFixedOfferRedeployERC20Permit
        - event: DirectLoanFixedOfferRedeployLoanLiquidated(indexed uint32,indexed address,indexed
            address,uint256,uint256,uint256,uint256,address)
          handler: handleDirectLoanFixedOfferRedeployLoanLiquidated
        - event: DirectLoanFixedOfferRedeployLoanRenegotiated(indexed uint32,indexed address,indexed
            address,uint32,uint256,uint256,uint256)
          handler: handleDirectLoanFixedOfferRedeployLoanRenegotiated
        - event: DirectLoanFixedOfferRedeployLoanRepaid(indexed uint32,indexed address,indexed
            address,uint256,uint256,uint256,uint256,uint256,address,address,address)
          handler: handleDirectLoanFixedOfferRedeployLoanRepaid
        - event: DirectLoanFixedOfferRedeployLoanStarted(indexed uint32,indexed address,indexed
            address,(uint256,uint256,uint256,address,uint32,uint16,uint16,address,uint64,address,address),(address,uint16,uint16))
          handler: handleDirectLoanFixedOfferRedeployLoanStarted
        - event: DirectLoanFixedOfferRedeployMaximumLoanDurationUpdated(uint256)
          handler: handleDirectLoanFixedOfferRedeployMaximumLoanDurationUpdated
        - event: DirectLoanFixedOfferRedeployOwnershipTransferred(indexed address,indexed address)
          handler: handleDirectLoanFixedOfferRedeployOwnershipTransferred
        - event: DirectLoanFixedOfferRedeployPaused(address)
          handler: handleDirectLoanFixedOfferRedeployPaused
        - event: DirectLoanFixedOfferRedeployUnpaused(address)
          handler: handleDirectLoanFixedOfferRedeployUnpaused
      file: ./src/direct-loan-fixed-offer-redeploy.ts
```
