### ISSUE TITLE
Unable to deploy subgraph with studio. 

### ISSUE THREAD

**Issue by tomwhiteman** [graphprotocol/graph-tooling#1274]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

I am trying to deploy my subgraph to studio on the goerli testnet. 

This is my `src/mapping.ts` file: 

```
import {
  NameRegistered as NameRegisteredEvent,
  NameRenewed as NameRenewedEvent
} from "../generated/SubscriptionSubdomainRegistrar/SubscriptionSubdomainRegistrar"
import { NameRegistered, NameRenewed } from "../generated/schema"

export function handleNameRegistered(event: NameRegisteredEvent): void {
  let entity = new NameRegistered(
    event.transaction.hash.concatI32(event.logIndex.toI32())
  )
  entity.node = event.params.node
  entity.expiry = event.params.expiry
  entity.owner = event.params.owner
  entity.subname = event.params.subname

  entity.blockNumber = event.block.number
  entity.blockTimestamp = event.block.timestamp
  entity.transactionHash = event.transaction.hash

  entity.save()
}

export function handleNameRenewed(event: NameRenewedEvent): void {
  let entity = new NameRenewed(
    event.transaction.hash.concatI32(event.logIndex.toI32())
  )
  entity.node = event.params.node
  entity.expiry = event.params.expiry

  entity.blockNumber = event.block.number
  entity.blockTimestamp = event.block.timestamp
  entity.transactionHash = event.transaction.hash

  entity.save()
}
```

This is my `subgraph.yaml`:

```
specVersion: 0.0.5
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: SubscriptionSubdomainRegistrar
    network: goerli
    source:
      address: "0x60e290D375Fa4A2edD703b0C7598eAB6b5F1Bd23"
      abi: SubscriptionSubdomainRegistrar
      startBlock: 8810871
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - NameRegistered
        - NameRenewed
      abis:
        - name: SubscriptionSubdomainRegistrar
          file: ./abis/SubscriptionSubdomainRegistrar.json
      eventHandlers:
        - event: NameRegistered(bytes32,uint256,indexed address,string)
          handler: handleNameRegistered
        - event: NameRenewed(bytes32,uint256)
          handler: handleNameRenewed
      file: ./src/subscription-subdomain-registrar.ts
```
This is my `schema.graphql`:
```
type NameRegistered @entity(immutable: true) {
  id: Bytes!
  node: Bytes! # bytes32
  expiry: BigInt! # uint256
  owner: Bytes! # address
  subname: String! # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type NameRenewed @entity(immutable: true) {
  id: Bytes!
  node: Bytes! # bytes32
  expiry: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
```

### Reproduction

graph cli v 0.45.2

### Steps to Reproduce the Bug or Issue

Follow the exact steps in the graph studio section. 

### Expected behavior

Expected subgraph to deploy. 

### Platform

Mac OS, graph cli v0.45.2
