### ISSUE TITLE
zkSync Alpha (zkSync2-testnet) not available on Studio but listed as available 

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-tooling#1367]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

zkSync Alpha is listed on Studio but this network is not available on the graph-cli.
The network slug for zkSync Alpha is zkSync2-testnet and can only be deployed to the Hosted Service. 

### Reproduction

nil

### Steps to Reproduce the Bug or Issue

Given a manifest like this, the graph-cli does not allow you to deploy.

```yaml
specVersion: 0.0.5
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Contract
    network: zkSync2-testnet
    source:
      address: "0x08158a6b5d4018340387d1a302f882e98a8bc5b4"
      abi: Contract
      startBlock: 0
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Block
      abis:
        - name: Contract
          file: ./abis/Contract.json
      blockHandlers:
        - handler: handleBlock
      file: ./src/contract.ts
```

You get an error like this:

  ` Error: The Subgraph Studio only allows subgraphs for these networks: mainnet, rinkeby, goerli, gnosis, chapel, optimism-goerli, clover, fantom, matic, fantom-testnet, 
    arbitrum-goerli, fuji, celo-alfajores, mumbai, aurora-testnet, near-testnet, optimism, optimism-goerli, theta-testnet-001, osmo-test-4, base-testnet, celo, arbitrum-one, avalanche, 
    zksync-era, sepolia, polygon-zkevm-testnet, polygon-zkevm`

### Expected behavior

nil

### Platform

    "@graphprotocol/graph-cli": "0.51.0",
    "@graphprotocol/graph-ts": "0.30.0"
