### ISSUE TITLE
Could not create WasmInstance from valid module with context: unknown import: `index::store.loadRelated` has not been defined'

### ISSUE THREAD

**Issue by hexzerodev** [graphprotocol/graph-tooling#1376]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Trying to run unit tests in my subgraph but getting an error:

```
Could not create WasmInstance from valid module with context: unknown import: `index::store.loadRelated` has not been defined'
```

Here the versions im using

```
"dependencies": {
    "@graphprotocol/graph-cli": "0.51.1",
    "@graphprotocol/graph-ts": "0.31.0"
  },
  "devDependencies": { "matchstick-as": "0.5.0" }
```

Here's a minimal reproducible example https://github.com/hexzerodev/subgraph-load-related-error

The error pops up when running `graph test`

### Reproduction

https://github.com/hexzerodev/subgraph-load-related-error

### Steps to Reproduce the Bug or Issue

```
1. npm install
2. graph test
```

### Expected behavior

Test to be compiled properly

### Platform

```
- OS: Mac
- NodeJS: 19.8.1
- `@graphprotocol/*` version(s): v0.51.1
```

### Subgraph Manifest

```
specVersion: 0.0.5
description: 'example of a subgraph'
repository: https://github.com/graphprotocol/graph-tooling.git
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: ExampleSubgraph
    network: mainnet
    source:
      address: '0x22843e74c59580b3eaf6c233fa67d8b7c561a835'
      abi: ExampleContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      entities:
        - ExampleEntity
        - OtherEntity
      abis:
        - name: ExampleContract
          file: ./abis/ExampleContract.json
      eventHandlers:
        - event: ExampleEvent(indexed string)
          handler: handleExampleEvent
```

### Subgraph GraphQL Schema

```
type ExampleEntity @entity {
  id: ID!

  optionalBoolean: Boolean
  requiredBoolean: Boolean!
  optionalBooleanList: [Boolean!]
  requiredBooleanList: [Boolean!]!

  optionalString: String
  requiredString: String!
  optionalStringList: [String!]
  requiredStringList: [String!]!

  optionalBytes: Bytes
  requiredBytes: Bytes!
  optionalBytesList: [Bytes!]
  requiredBytesList: [Bytes!]!

  optionalInt: Int
  requiredInt: Int!
  optionalIntList: [Int!]
  requiredIntList: [Int!]!

  optionalBigInt: BigInt
  requiredBigInt: BigInt!
  optionalBigIntList: [BigInt!]
  requiredBigIntList: [BigInt!]!

  optionalReference: OtherEntity
  requiredReference: OtherEntity!
  optionalReferenceList: [OtherEntity!]
  requiredReferenceList: [OtherEntity!]!
}

type OtherEntity @entity {
  id: ID!
}

type User @entity {
  id: ID!
  objects: [Object!]! @derivedFrom(field: "owner")
}

type Object @entity {
  id: ID!
  owner: User
}
```
