### ISSUE TITLE
Cannot set `startBlock` for Substreams data source

### ISSUE THREAD

**Issue by DenisCarriere** [graphprotocol/graph-tooling#1391]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Cannot provide `startBlock: 1397553` for when using Substreams data source.

```graphql
specVersion: 0.0.6
description: ERC20 Ethereum (powered by Substreams)
repository: https://github.com/pinax-network/substreams-cookbook.git
schema:
  file: ./schema.graphql

dataSources:
  - kind: substreams
    name: erc20
    network: Mainnet
    source:
      startBlock: 1397553
      package:
        moduleName: graph_out
        file: ./erc20-v0.1.0.spkg
    mapping:
      kind: substreams/graph-entities
      apiVersion: 0.0.5
```

### Reproduction

https://github.com/pinax-network/substreams-cookbook/tree/main/erc20

### Steps to Reproduce the Bug or Issue

```
graph build
```

Error message:

```
✔ Apply migrations
✖ Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:

  Path: dataSources > 0 > source
  Unexpected key in map: startBlock
Error: Error in subgraph.yaml:

  Path: dataSources > 0 > source
  Unexpected key in map: startBlock
```

### Expected behavior

Additionally to Substreams `startBlock`, should be able to provide `startBlock` to Subgraph when using Substreams data source.

### Platform

$ graph --version
@graphprotocol/graph-cli/0.51.2 darwin-arm64 node-v20.2.0

### Subgraph Manifest

not sure where to include: `startBlock: 1397553`

```yaml
dataSources:
  - kind: substreams
    name: erc20
    network: Mainnet
    source:
      package:
        moduleName: graph_out
        file: ./erc20-v0.1.0.spkg
    mapping:
      kind: substreams/graph-entities
      apiVersion: 0.0.5
```
