### ISSUE TITLE
Codegen does not import `Address` type if `file/ipfs` template is declared first under `templates`

### ISSUE THREAD

**Issue by dimitrovmaksim** [graphprotocol/graph-tooling#1453]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Declaring the templates in the following order
```yaml
templates:
  - kind: ethereum/contract
    name: GraphTokenLockWallet
    network: mainnet
    source:
      abi: GraphTokenLockWallet
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/token-lock-wallet.ts
      entities:
        - TokenLockWallet
      abis:
        - name: GraphTokenLockWallet
          file: ./abis/GraphTokenLockWallet.json
      eventHandlers:
        - event: TokensReleased(indexed address,uint256)
          handler: handleTokensReleased
  - name: TokenMetadata
    kind: file/ipfs
    mapping:
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      handler: handleMetadata
      entities:
        - TokenMetadata
      abis:
        - name: GraphTokenLockWallet
          file: ./abis/GraphTokenLockWallet.json
```

will generate the following imports in `generated/templates.ts`:
```ts
import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";
```

but if the `file/ipfs` template is declared before the `ethereum/contract` the Address import is missing

```ts
templates:
  - name: TokenMetadata
    kind: file/ipfs
    mapping:
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      handler: handleMetadata
      entities:
        - TokenMetadata
      abis:
        - name: GraphTokenLockWallet
          file: ./abis/GraphTokenLockWallet.json
  - kind: ethereum/contract
    name: GraphTokenLockWallet
    network: mainnet
    source:
      abi: GraphTokenLockWallet
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/token-lock-wallet.ts
      entities:
        - TokenLockWallet
      abis:
        - name: GraphTokenLockWallet
          file: ./abis/GraphTokenLockWallet.json
      eventHandlers:
        - event: TokensReleased(indexed address,uint256)
          handler: handleTokensReleased
```

`generated/templates.ts`

```ts
import { DataSourceTemplate, DataSourceContext } from "@graphprotocol/graph-ts";
```

### Reproduction

https://github.com/LimeChain/demo-subgraph/tree/codegen-missing-imports

### Steps to Reproduce the Bug or Issue

1. Go to https://github.com/LimeChain/demo-subgraph
2. Clone the repo
3. Fetch and checkout into `codegen-missing-imports`
4. Install deps
5. Run codegen
6. Check imports in `generated/templates.ts`. Address import is missing, but is required by `GraphTokenLockWallet` create/createWithContext
7. Switch order of declared templates in subgraph.yaml
8.  Run codegen again
9. Check imports in `generated/templates.ts`. Address import is present

### Expected behavior

It should import all required types

### Platform

@graphprotocol/graph-cli/0.57.0 darwin-arm64 node-v18.17.0
