### ISSUE TITLE
Incorrect builds when building multiple data sources

### ISSUE THREAD

**Issue by PaulRBerg** [graphprotocol/graph-tooling#2046]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Given this subgraph manifest:

<details><summary>Details</summary>
<p>

```yaml
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
specVersion: "1.3.0"
description: "The Graph indexer for Sablier Flow"
repository: "https://github.com/sablier-labs/indexers"
schema:
  file: "../schema.graphql"
dataSources:
  - kind: "ethereum/contract"
    name: "SablierFlow_v1_0"
    network: "ethereum"
    context:
      alias:
        data: "FL"
        type: "String"
      chainId:
        data: "1"
        type: "BigInt"
      version:
        data: "v1.0"
        type: "String"
    source:
      address: "0x2d9221a63e12aa796619cb381ec4a71b201281f5"
      abi: "SablierFlow"
      startBlock: 21330577
    mapping:
      apiVersion: "0.0.9"
      kind: "ethereum/events"
      language: "wasm/assemblyscript"
      abis:
        - name: "SablierFlow"
          file: "../../../abi/flow-v1.0/SablierFlow.json"
        - name: "ERC20"
          file: "../../../abi/ERC20.json"
        - name: "ERC20Bytes"
          file: "../../../abi/ERC20Bytes.json"
      entities:
        - "Action"
        - "Asset"
        - "Batch"
        - "Batcher"
        - "Broker"
        - "Contract"
        - "Stream"
        - "Watcher"
      eventHandlers:
        - event: "Approval(indexed address,indexed address,indexed uint256)"
          handler: "handleApproval"
        - event: "ApprovalForAll(indexed address,indexed address,bool)"
          handler: "handleApprovalForAll"
        - event: "Transfer(indexed address,indexed address,indexed uint256)"
          handler: "handleTransfer"
        - event: "AdjustFlowStream(indexed uint256,uint256,uint128,uint128)"
          handler: "handleAdjustFlowStream"
        - event: "CreateFlowStream(uint256,indexed address,indexed address,uint128,indexed address,bool)"
          handler: "handleCreateFlowStream"
        - event: "DepositFlowStream(indexed uint256,indexed address,uint128)"
          handler: "handleDepositFlowStream"
        - event: "PauseFlowStream(indexed uint256,indexed address,indexed address,uint256)"
          handler: "handlePauseFlowStream"
        - event: "RefundFromFlowStream(indexed uint256,indexed address,uint128)"
          handler: "handleRefundFromFlowStream"
        - event: "RestartFlowStream(indexed uint256,indexed address,uint128)"
          handler: "handleRestartFlowStream"
        - event: "VoidFlowStream(indexed uint256,indexed address,indexed address,address,uint256,uint256)"
          handler: "handleVoidFlowStream"
        - event: "WithdrawFromFlowStream(indexed uint256,indexed address,indexed address,address,uint128,uint128)"
          handler: "handleWithdrawFromFlowStream"
      file: "../mappings/v1.0/index.ts"
  - kind: "ethereum/contract"
    name: "SablierFlow_v1_1"
    network: "ethereum"
    context:
      alias:
        data: "FL2"
        type: "String"
      chainId:
        data: "1"
        type: "BigInt"
      version:
        data: "v1.1"
        type: "String"
    source:
      address: "0x3df2aaede81d2f6b261f79047517713b8e844e04"
      abi: "SablierFlow"
      startBlock: 21718688
    mapping:
      apiVersion: "0.0.9"
      kind: "ethereum/events"
      language: "wasm/assemblyscript"
      abis:
        - name: "SablierFlow"
          file: "../../../abi/flow-v1.1/SablierFlow.json"
        - name: "ERC20"
          file: "../../../abi/ERC20.json"
        - name: "ERC20Bytes"
          file: "../../../abi/ERC20Bytes.json"
      entities:
        - "Action"
        - "Asset"
        - "Batch"
        - "Batcher"
        - "Broker"
        - "Contract"
        - "Stream"
        - "Watcher"
      eventHandlers:
        - event: "Approval(indexed address,indexed address,indexed uint256)"
          handler: "handleApproval"
        - event: "ApprovalForAll(indexed address,indexed address,bool)"
          handler: "handleApprovalForAll"
        - event: "Transfer(indexed address,indexed address,indexed uint256)"
          handler: "handleTransfer"
        - event: "AdjustFlowStream(indexed uint256,uint256,uint128,uint128)"
          handler: "handleAdjustFlowStream"
        - event: "CreateFlowStream(uint256,indexed address,indexed address,uint128,indexed address,bool)"
          handler: "handleCreateFlowStream"
        - event: "DepositFlowStream(indexed uint256,indexed address,uint128)"
          handler: "handleDepositFlowStream"
        - event: "PauseFlowStream(indexed uint256,indexed address,indexed address,uint256)"
          handler: "handlePauseFlowStream"
        - event: "RefundFromFlowStream(indexed uint256,indexed address,uint128)"
          handler: "handleRefundFromFlowStream"
        - event: "RestartFlowStream(indexed uint256,indexed address,uint128)"
          handler: "handleRestartFlowStream"
        - event: "VoidFlowStream(indexed uint256,indexed address,indexed address,address,uint256,uint256)"
          handler: "handleVoidFlowStream"
        - event: "WithdrawFromFlowStream(indexed uint256,indexed address,indexed address,address,uint128,uint128)"
          handler: "handleWithdrawFromFlowStream"
      file: "../mappings/v1.1/index.ts"
```

</p>
</details> 

I am getting the following incorrect names in the logs generated via running `graph build`:

<img width="400" src="https://github.com/user-attachments/assets/a0b96588-5112-4a23-bc50-82132aa83c98"/>

### Reproduction

https://github.com/sablier-labs/indexers/tree/f841168cb2bed990ec2fed2c7f256571e6111e98

### Steps to Reproduce the Bug or Issue

1. Go to the repo I linked to
2. Install dependencies with `pnpm install`
3. Run this command:

```sh
pnpm graph build --output-dir src/graph/lockup/build src/graph/lockup/manifests/ethereum.yaml
```

### Expected behavior

The contract names should have been correctly matched in the logs, e.g.

```text
  Compile data source: SablierLockup_v2_0 => src/graph/lockup/build/SablierLockup_v2_0/SablierLockup_v2_0.wasm
```

### Platform

- macOS 15.5
- NodeJS: v22.13.1
- `@graphprotocol/graph-cli` version: 0.97.1
- `@graphprotocol/graph-ts` version: 0.38.1
