### ISSUE TITLE
Codegen fails with nondescript error

### ISSUE THREAD

**Issue by aazhou1** [graphprotocol/graph-tooling#962]
Running `graph codegen` fails with the following error message `Failed to load subgraph from subgraph.yaml: entry.get is not a function`. Not sure what `entry.get` is referring to.

**Comment by azf20** [comment]
Hi! What version of graph cli are you using and can you share your subgraph.yaml?

**Comment by ricardopinto** [comment]
Also running into this error while executing `yarn codegen` and my graph-cli version is `0.35.0`.

I'm learning the graph protocol and trying to index ERC20 token events from a private geth network, into a local graph-node. The codebase is a clone of [graphprotocol/example-subgraph](https://github.com/graphprotocol/example-subgraph) and this is how the files look like:

subgraph.yaml:
```yaml
specVersion: 0.0.4
description: Gravatar for Ethereum
repository: https://github.com/graphprotocol/example-subgraph
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: USD
    network: mainnet
    source:
      address: '0x0b95FddBB1d1a9442D55B00Cf599966b39455176'
      abi: USDabi
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - TransferEntity
        - ApprovalEntity
      abis:
        - name: USDabi
          file: ./abis/USD.json
      eventHandlers:
        - event: Transfer(address indexed,address indexed,uint256)
          handler: handleUSDTransfer
        - event: Approval(address indexed,address indexed,uint256)
          handler: handleUSDApproval
      file: ./src/mapping.ts
```

abis/USD.json:
```json
[
  "constructor()",
  "event Approval(address indexed,address indexed,uint256)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "event Transfer(address indexed,address indexed,uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function balanceOf(address) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function decreaseAllowance(address,uint256) returns (bool)",
  "function increaseAllowance(address,uint256) returns (bool)",
  "function mint(address,uint256)",
  "function name() view returns (string)",
  "function owner() view returns (address)",
  "function renounceOwnership()",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address,uint256) returns (bool)",
  "function transferFrom(address,address,uint256) returns (bool)",
  "function transferOwnership(address)"
]
```

docker-compose.yaml:
```yaml
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      # Change next line if you want to connect to a different JSON-RPC endpoint
      ethereum: 'mainnet:http://geth-private-network.com'
      GRAPH_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```

schema.graphql:
```graphql
type TransferEntity @entity {
  id: ID!
  from: String!
  to: String!
  amount: String!
}

type ApprovalEntity @entity {
  id: ID!
  from: String!
  to: String!
  amount: String!
}
```

The `src/mapping.ts` file is missing types to import from and I'm guessing these types would be generated out of `yarn codegen`. Don't know what to do here.
